services:
  shipnow:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_ENV=prod
      - REDIS_0_ADDR=redis:6379
    restart: unless-stopped
    ports:
      - "8080:8080"
    command: --bind 0.0.0.0:8080
  redis:
    image: redis:latest
    restart: unless-stopped
